- .github/workflows/_shared-docs-build-publish-surge.yml
Resolves #12 
Related to #10 
This pins the version of `surge@0.23.0`, which happens to be current version being installed.
It also separately installs `colors@1.4.0` to temporarily resolve #12, until one of either the colors package is back under control or surge pins its dependency or both.
I would like to further look into whether there's an even better way to do this. I looked around for a bit, messing with `packages-lock.json` and `npm shrinkwrap` but I didn't come up with anything viable (as I'm not well-versed in nodejs at all).
> pin surge and colors [npm]

- .github/workflows/_shared-docs-build-pr.yml
Fixes #3. See https://github.com/ansible-collections/community.docker/pull/280 as an example; it was run with https://github.com/ansible-collections/community.docker/commit/c4a009a5375793a750584752868751e535ee510c.
> Use merge commit for PR instead of HEAD commit of PR

- .github/workflows/_shared-docs-build-publish-surge.yml
related: 
- #12 
- https://github.com/sintaxi/surge/issues/469
`surge` has updated their `colors` pin with a new release, pinning to that one
tested externally in: https://github.com/briantist/gha-junk/runs/4754282432?check_suite_focus=true
> pin surge@0.23.1, remove explicit colors pin #12

- .github/workflows/_shared-docs-build-pr.yml
- actions/ansible-docs-build-diff/action.yml
This extends the ansible-docs-build-diff action to delete `.js` and `.inv` files before doing the diff. Since this is after uploading the artefact, it shouldn'd break anything :)
I'm resuing the same branch name as before so I don't have to change community.docker's main branch ;) I've tested this in https://github.com/ansible-collections/community.docker/pull/280 as well; as you can see the diff there is now only the modified HTML file.
Fixes #2.
This cannot be merged yet since one commit needs to be reverted (the one changing the workflow). I'll do that after review.
> Ignore .js and .inv files for diff

- .github/workflows/_shared-docs-build-pr.yml
Related to:
- #14 
- #3 
The changes in #14 result in a failed build when the PR is closed/merged, because the special merge "branch" doesn't exist anymore.
However, I have found that `github.event.pull_request.merge_commit_sha` does exist on closed/merged/reopened PRs. It does not exist on the first opened event though (whereas the merge branch _does_).
I also did some tests showing that when both the merge SHA and the merge branch exist, the content of their checkouts are exactly the same: https://github.com/briantist/gha-junk/runs/4827842600?check_suite_focus=true
This PR sets an output var for the ref we'll be using in the PR checkout. We start with the SHA because that will either be set, or blank. If the SHA is blank, then we fall back to the merge "branch".
I believe this will …
> pr workflow - use merge SHA when available

- .github/workflows/test-action-build-init.yml
- .test/simple-build/build.sh
- .test/simple-build/requirements.txt
- .test/simple-build/src/index.html
- .test/simple-build/src/other.html
Has a slight overlap with #18 (the `.test` directory) but should be no conflicts.
These are the first round of tests for the init action.
> `ansible-docs-build-init` - first tests

- .github/workflows/generate-wiki-docs.yml
- .gitignore
- .internal/ansible/ansible_collections/internal/gha_docs/README.md
- .internal/ansible/ansible_collections/internal/gha_docs/galaxy.yml
- .internal/ansible/ansible_collections/internal/gha_docs/meta/runtime.yml
- .internal/ansible/ansible_collections/internal/gha_docs/playbooks/generate_docs.yml
- .internal/ansible/ansible_collections/internal/gha_docs/roles/generate/files/output/.gitignore
- .internal/ansible/ansible_collections/internal/gha_docs/roles/generate/meta/argument_specs.yml
- .internal/ansible/ansible_collections/internal/gha_docs/roles/generate/tasks/main.yml
- .internal/ansible/ansible_collections/internal/gha_docs/roles/generate/templates/action.md.j2
- .internal/ansible/ansible_collections/internal/gha_docs/roles/generate/templates/workflow.md.j2
This is some messing around I did to try to generate markdown from the action and shared workflow YAML files.
I did in Ansible, as an "internal" collection with a role and playbook.
I figured, as a bonus, we could use this internal collection for some of the tests in terms of actually generating documentation (the role has an argspec 😎).
This also has a workflow that would run the Ansible, and synchronize the changes to those files to the repo's wiki.
The worklow is set to run on `push` (was going to add `workflow_dispatch` but for now leaving it out, because the commit info is not available in the event, would have to retrieve it separately).
~`pull_request` trigger is added just for this PR, so I can test it a little; that must be removed before merging.~
Testing stuff has been removed, …
> [experimental] generate wiki docs from action/workflow YAML

- .github/workflows/generate-wiki-docs.yml
- .internal/ansible/ansible_collections/internal/gha_docs/roles/generate/tasks/main.yml
With #21 landed, found a few issues:
- if fails on forks (unless the wiki is enabled, and the `actions/` and `workflows/` directories existed in the repo)
- the setting I was using for `GH_NAME` was wrong; it was supposed to be a username.
So this PR makes the following changes:
- we set an env var `SHOULD_RUN` that checks whether we're running in the main repo, or whether a secret named `GENERATE_WIKI_PAGES` is set to `yes`
- all steps in the job are now conditional, and only run if `SHOULD_RUN` is true
- the Ansible role to generate the docs ensures the target directory exists
- added `.internal/ansible/**` to the list of paths that trigger the workflow
- [minor] moved adding the trailing forward slash on the wiki dir to the action invocation
So, on **forks**, this workflow will no …
> wiki docs generation - fixups and fork ops

- .internal/ansible/ansible_collections/internal/gha_docs/roles/generate/tasks/main.yml
- .internal/ansible/ansible_collections/internal/gha_docs/roles/generate/templates/workflow.md.j2
Just realized an oversight in the generated docs for shared workflows: "secrets" are defined separately from other inputs. This PR adds them to the docs (we are currently using a defined secret in the surge workflow).
Tested generation locally.
> show defined secrets in workflow docs

- .github/workflows/test-action-build-html.yml
- .github/workflows/test-action-build-init.yml
- actions/ansible-docs-build-html/action.yml
Fixes: #24 
- fix typos in workflow triggers that prevented tests running
- add trailing slash to `rsync` command for `copy-build` option
- add tests to ensure artifact does not contain additional directory
- add tests that add a trailing slash on inputs to ensure it adding it again to rsync doesn't break
> build-html - ensure artifact root matches build html root

- .github/workflows/_shared-docs-build-pr.yml
- .github/workflows/_shared-docs-build-push.yml
- .github/workflows/test-action-build-init.yml
- actions/ansible-docs-build-init/action.yml
Adds three new options to the build-init action (and pass-through options on the shared workflows):
- `lenient`
- `fail-on-error`
- `antsibull-version`
Resolves: #11
Resolves: #1
Resolves: #26 
Note: `--fail-on-error` (added in https://github.com/ansible-community/antsibull/pull/393) is not released as of this writing.
The tests are written in such a way (by accident really) that this won't cause them to fail when using `--fail-on-error` with a version of `antisbull` is used that doesn't support it.
I think that's ok; it will be released soon, and we aren't really looking to test antsibull itself, so it's probably better that way... open to alternate takes on that, but it will be more complicated for us to re-work the tests so that if detects this as a "failure", only to have the point …
> build-init - lenient, fail-on-error, antsibull-version

- .github/workflows/_shared-docs-build-pr.yml
- .github/workflows/_shared-docs-build-push.yml
At least until milestone has been advanced. That should fix the docs build issues due to the new ansible-doc parameter missing...
> Use stable-2.13 instead of milestone as default

- .github/workflows/_shared-docs-build-pr.yml
- .github/workflows/_shared-docs-build-publish-surge.yml
- .github/workflows/_shared-docs-build-push.yml
- .github/workflows/generate-wiki-docs.yml
- .github/workflows/test-action-build-html.yml
- .github/workflows/test-action-build-init.yml
- actions/ansible-docs-build-comment/action.yml
- actions/ansible-docs-build-diff/action.yml
- actions/ansible-docs-build-html/action.yml
Most of GutHub's actions have had a major version bump, primarily to bump their required version of Node, because the one being used is EoL soon.
This updates those versions in the composite actions and workflows.
The `setup-python` action also added cache support (before the major version bump). Enabling that too; it only caches the pip cache, not installed packages, so it won't save us from install time (Ansible itself being the major time taker there), only from download time, but that also means we will not ever end up with stale packages due to the cache.
We don't actually have a good set of files in this repo to hash as a cache key, but still I figure, can't hurt.
If this ends up worse for whatever reason, we can remove it.
> bump actions versions, cache pip

- .github/workflows/_shared-docs-build-pr.yml
- .github/workflows/_shared-docs-build-push.yml
- .github/workflows/generate-wiki-docs.yml
- .github/workflows/test-action-build-init.yml
#32 added caching for setup-python, with the caveat that if it caused any problems we'd remove it: and it is breaking in PR workflow at least, because we set up python before checking out, so it can't find the cache key files.
I could consider tweaking the order of things, but I think it's better to remove caching for now and not consider re-adding until we have tests for the workflows (#29) , as the benefit was likely to be minimal anyway.
> disable python cache

- .github/workflows/_shared-docs-build-pr.yml
Resolves #36 
Changing to use the merge branch in all cases except on PR close where it's not available.
After thinking through this, I think this is the best change to make, at least in the short term:
- the current situation is plain broken most of the time
- I don't think re-runs are a significant enough issue to worry about them for the most part; I can't think of a good use case for re-running against an old commit and expecting results consistent with the state of the PR and the target at the time of the original run (I don't think we were addressing this anyway).
- Although we're not comparing against the point where the PR branched from the target branch necessarily, I think the merge branch is better for what we're trying to achieve, which is seeing what the end result will be …
> fix PR workflow checkouts

- .github/workflows/_shared-docs-build-pr.yml
- .github/workflows/_shared-docs-build-push.yml
The community.aws collection relies on a documentation fragment from amazon.aws.
In an ideal world this could be cloned from the same branch that the PR's against (eg `stable-3` of amazon.aws and `stable-3` of community.aws), however, this is a reasonable first approximation.
fixes: #40
> Support installing extra collections

- .github/workflows/_shared-docs-build-publish-gh-pages.yml
This is a reusable workflow for publishing to GitHub Pages. 
This is intended to be an opinionated, specific way of doing so that supports multiple simultaneous docs builds within a single GitHub Pages site, not a general workflow to have a high degree of customizability.
The reason for that, is that the bulk of the "work" of publishing to GH pages is handled by a single action, [peaceiris/actions-gh-pages](https://github.com/peaceiris/actions-gh-pages), which can be used directly for anyone wishing to do something simpler or more custom. Alternatively, "publishing" to GitHub Pages is done via commit and push, so users who don't want to use the action can similarly put something together using git commands.
Or this workflow can have the `destination-dir` overridden, which is really where …
> first pass at a GitHub Pages publishing shared workflow

- .github/workflows/_shared-docs-build-push.yml
This modifies the push build workflow so that you can:
- specify whether or not to upload the build as an artifact (defaults to `true`, no change in behavior)
- specify which ref to checkout (defaults to none which defaults to actions/checkout default, no change in behavior)
These changes make the workflow useful for running a "validation" job, by changing the lenient and fail-on-error options. This was already possible for push workflows, but the artifact uploaded was redundant and couldn't be turned off.
For PRs, this was not possible with `pull_request_target` events (which we usually use) because we had no way to tell the workflow to use the PR ref (the default would have been the PR target, like `main`). Now we can tell the workflow to use the merge commit or whatever on PRs. …
> workflow shared-docs-build-push: add `artifact-upload` and `build-ref` options

- samples/README.md
- samples/pr-build-and-comment.yml
- samples/pr-with-publish-to-gh-pages.yml
- samples/push-with-build.yml
- samples/push-with-publish-to-gh-pages.yml
some samples folks can use to actually start using this stuff
> add some sample workflows

- .github/workflows/_shared-docs-build-pr.yml
- .github/workflows/test-action-build-init.yml
- actions/ansible-docs-build-init/action.yml
Sometimes you don't want to add extra collections to the docs build to resolve some labels, but just provide these label targets. This is useful for community.general which has redirects to infoblox.nios_modules, but we don't want to install that collection to build the docs (it's not under our control and might produce new build errors). Building without that collection gives warnings such as
```
.../rst/collections/community/general/nios_a_record_module.rst:21: WARNING: undefined label: ansible_collections.infoblox.nios_modules.nios_a_record_module
```
which would require us to be lenient on docs build errors. With this new option we can add a file (rst/_targets.rst) that contains the given labels.
(Not yet tested.)
> Allow to provide extra labels

- actions/ansible-docs-build-init/action.yml
See https://github.com/ansible-collections/community.general/runs/7003339788?check_suite_focus=true
```
/home/runner/work/_temp/docsbuild/base/rst/_targets.rst:2: WARNING: Field list ends without a blank line; unexpected unindent.
/home/runner/work/_temp/docsbuild/base/rst/_targets.rst:30: WARNING: malformed hyperlink target.
```
> Fix _targets.rst file: add needed newline, prevent bad labels due to empty lines

- .github/workflows/_shared-docs-build-pr.yml
Avoid that errors in the PR target branch fail the docs build.
For example in https://github.com/ansible-collections/community.general/pull/4881 the docs build fails because while the PR fixes the issues, the docs build is never run with these fixes.
> Shared PR docs workflow: Be nicer during the BASE build

- .github/workflows/_shared-docs-build-push.yml
Because antisibull-docs doesn't support adding extra intersphinx links yet (https://github.com/ansible-community/antsibull-docs/issues/35) we need a way to temporarily inject additional links for build-push as well as build-pr
> Allow for provide-link-targets during build-push as well as build-pr

- .github/workflows/_shared-docs-build-pr.yml
- .github/workflows/_shared-docs-build-push.yml
Now that stable-2.14 has been branched, switch to that one since it supports rendering test and filter docs :tada:
> Bump stable-2.13 to stable-2.14

- .github/workflows/_shared-docs-build-pr.yml
- .github/workflows/_shared-docs-build-push.yml
- .github/workflows/test-action-build-init.yml
- actions/ansible-docs-build-init/action.yml
Following the release of antsibull-docs 1.7.0 we now have access to --intersphinx when initializing sphinx.
https://github.com/ansible-community/antsibull-docs/pull/44
This means that we can automatically generate links between multiple docs sites
> Support adding intersphinx links

- .github/workflows/_shared-docs-build-pr.yml
- .github/workflows/_shared-docs-build-push.yml
- .github/workflows/generate-wiki-docs.yml
- .github/workflows/test-action-build-init.yml
- actions/ansible-docs-build-html/action.yml
- actions/ansible-docs-build-init/action.yml
> Replace set-output by GITHUB_OUTPUT

- .github/workflows/_shared-docs-build-pr.yml
- .github/workflows/_shared-docs-build-push.yml
- .github/workflows/test-action-build-init.yml
- actions/ansible-docs-build-init/action.yml
That would allow to have the collections docs to be at https://ansible-collections.github.io/community.dns/branch/main/ instead of having them in a subdirectory https://ansible-collections.github.io/community.dns/branch/main/collections/community/dns/.
> Allow to pass --squash-hierarchy to 'antsibull-docs sphinx-init'

- .github/workflows/_shared-docs-build-pr.yml
- .github/workflows/_shared-docs-build-push.yml
It looks like the shared workflows in #58 had typos. Unfortunately they aren't tested, so I only noticed after merging :(
> Fix typo introduced in #58

- .github/workflows/_shared-docs-build-publish-gh-pages.yml
Right now the shared workflow triggers a warning (`Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: peaceiris/actions-gh-pages@068dc23d9710f1ba62e86896f84735d869951305`). Let's upgrade the action to 3.9.0 which fixes that (https://github.com/peaceiris/actions-gh-pages/blob/v3.9.0/CHANGELOG.md#feat).
> Bump peaceiris/actions-gh-pages to 3.9.0.

- .github/workflows/_shared-docs-build-pr.yml
- .github/workflows/_shared-docs-build-push.yml
- actions/ansible-docs-build-init/action.yml
Allows to use branches form other forks of antsibull-docs.
I'm using another branch (https://github.com/ansible-community/github-docs-build/compare/main...felixfontein:github-docs-build:repo) to test this in community.dns (https://github.com/ansible-collections/community.dns/commit/075d3a098438e54fffb3630c75b698fd237df1ed, https://github.com/ansible-collections/community.dns/pull/23).
> Add a way to modify the antsibull-docs repository used when installing antsibull-docs

- .github/workflows/_shared-docs-build-pr.yml
- .github/workflows/_shared-docs-build-push.yml
- .github/workflows/generate-wiki-docs.yml
- .github/workflows/test-action-build-init.yml
Ref: https://github.com/ansible-collections/news-for-maintainers/issues/48
- Use Python 3.11 for build action testing.
- Use ansible-core 2.15 on Python 3.11 for Wiki.
- Bump defaults for shared workflows to stable-2.15 and Python 3.10.
> Bump ansible-core and Python versions

- .github/workflows/_shared-docs-build-pr.yml
- .github/workflows/_shared-docs-build-push.yml
- .github/workflows/test-action-build-init.yml
- actions/ansible-docs-build-init/action.yml
Fixes https://github.com/ansible-community/antsibull-docs/issues/236.
> Allow to append something to conf.py

- .github/dependabot.yml
Some of the actions we're using have newer versions, which now results in warnings (see for example https://github.com/ansible-collections/community.crypto/actions/runs/7661373091). Manually remembering to updating them is annoying, so let's use Dependabot :)
I'm not sure whether this config covers the actions as well, but I'd say let's try and then see whether it needs adjustment.
> Add basic Dependabot config

- .github/dependabot.yml
It seems that by default it only updates the workflows, but not the actions.
Adding entries for the actions should solve this. I hope :)
> Use Dependabot also for actions

- .github/workflows/_shared-docs-build-publish-gh-pages.yml
This includes the latest commit, https://github.com/peaceiris/actions-gh-pages/commit/4eb285e828117bca26638192c3ed309c622e7bad, which removes the annoying warning.
Changes: https://github.com/peaceiris/actions-gh-pages/compare/373f7f263a76c20808c831209c920827a82a2847..4eb285e828117bca26638192c3ed309c622e7bad
Unfortunately there is no new release yet, so I've used the commit hash of the latest commit (which happens to be the commit bumping Node).
I have not updated the version comment in the hope that Dependabot will do this soon when a new version is out (which I hope will be soon, no idea whether that will actually happen). I'm not sure whether this is a good idea, since now the comment is definitely incorrect. @briantist WDYT?
> Bump peaceiris/actions-gh-pages action.

- .github/workflows/_shared-docs-build-publish-gh-pages.yml
- samples/pr-build-and-comment.yml
- samples/pr-with-publish-to-gh-pages.yml
- samples/push-with-publish-to-gh-pages.yml
I've tried integrating updating GH Pages into the shared workflow (`_shared-docs-build-publish-gh-pages.yml`), and after some tries it seems to work. This PR adds a new option, `publish-gh-pages-branch`, which needs to be explicitly enabled like this: https://github.com/ansible-collections/community.hrobot/commit/933f952c14072f635fb43c35f94dfe9459007fc5 (obviously without pointing to the workflow in my branch once this is merged ;) )
Successful run: https://github.com/ansible-collections/community.hrobot/actions/runs/9702624870. That run made https://ansible-collections.github.io/community.hrobot/pr/114/firewall_module.html#synopsis show `Test!` as the last paragraph of the `Description` (before it was `test`).
I'm not sure whether this is the best solution, and I'm also a bit surprised …
> Add option publish-gh-pages-branch

- .github/workflows/_shared-docs-build-pr.yml
- .github/workflows/_shared-docs-build-push.yml
> Update Python to 3.11, and the default ansible-core branch to stable-2.17

- .github/workflows/test-action-build-html.yml
#96 broke one test: https://github.com/ansible-community/github-docs-build/actions/runs/12331168792/job/34417458802
It's kind of annoying that this didn't fail in the PR, but only after merging...
> Fix copy'n'paste error in tests

- .github/workflows/_shared-docs-build-pr.yml
- .github/workflows/_shared-docs-build-push.yml
There's another bug in #96 which I unfortunately only noticed after merging some PRs, since the PR docs workflow in community.docker for some reason still used an older branch of mine instead of `main` of this repo... In any case, when reading https://github.com/actions/github-script?tab=readme-ov-file#use-env-as-input I apparently missed the most important part...
> Make sure variables are taken from environment before being used
